export const GET_FILTERED_JOB_REQUEST = "GET_FILTERED_JOB_REQUEST";
export const GET_FILTERED_JOB_SUCCESS = "GET_FILTERED_JOB_SUCCESS";
export const GET_FILTERED_JOB_FAILURE = "GET_FILTERED_JOB_FAILURE";